import fused from "../images/fused.gif";
import prospa from "../images/prospa.gif";
import denukan from "../images/denukan.gif";

export const fakeData = [
   {
      id: 1,
      name: "fused Afrika",
      img: fused,
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "typescript",
      framework3: "full stack",
      repo: "https://github.com/eakinloose/school_blog.git",
      framework4: "styled-components",
      link: "https://www.fusedafrika.com",
   },
   {
      id: 2,
      name: "prospa dashboard",
      img: prospa,
      desc: "Prospa is a technology company building the operating system for African entrepreneurs and businesses.",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com/eakinloose/prospa.git",
      framework4: "styled-components",
      link: "https://nuelzprospa.netlify.app/",
   },
   {
      id: 4,
      name: "Denukan.com",
      img: denukan,
      desc: "a Company organized principally to provide quality services to its various customers in the areas of Technology and Financial Consultancy.",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com/eakinloose/denukan.git",
      framework4: "styled-components",
      link: "https://www.denukan.com",
   },
   {
      id: 5,
      name: "Koʻza shoʻrva",
      img: "https://i.ibb.co/7Q8K8T1/kuza-shurpa-sm.jpg",
      desc: "fugiat commodo anim. Sunt officia esse labore occaecat fugiat do quis et adipisicing voluptate id.",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 6,
      name: "Lagʻmon",
      img: "https://i.ibb.co/wrvQ7gf/lagman-sm.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 7,
      name: "fused Afrika",
      // img: "https://i.ibb.co/FsD3Lgc/manti.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      img: "https://i.ibb.co/9pVmMxr/kazan-kabob.jpg",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 8,
      name: "Moshxoʻrda",
      img: "https://i.ibb.co/RNnFWvZ/moshkhurda-sm.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 9,
      name: "Noʻhat Shorak",
      img: "https://i.ibb.co/8B2wzQz/nohat-shorak.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 10,
      name: "one burner",
      img: "https://i.ibb.co/z719sZr/norin.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 11,
      name: "Shashlik",
      img: "https://i.ibb.co/fSvtzFg/shashlik-sm.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 12,
      name: "Tuxum Barak",
      img: "https://i.ibb.co/qjVrmMQ/tukhum-barak-sm.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
   {
      id: 13,
      name: "Somsa rgtdvds",
      img: "https://i.ibb.co/rQCBMcS/samosa-sm.jpg",
      desc: "a networking platform fortertiary institution student in afrika",
      framework: "react",
      framework2: "javascript",
      framework3: "frontend",
      repo: "https://github.com",
      framework4: "styled-components",
      link: "https://nuelztodo.netlify.app/",
   },
];
